<MyOwnLabel@Label>
    font_size: '25sp'
    valign: 'middle'
    halign: 'left'
    text_size: self.size

<Container>:
    rows: 3
    text_input: text_input
    label_hours: label_hours
    label_minutes: label_minutes
    label_seconds: label_seconds
    label_m_seconds: label_m_seconds
    label_weeks: label_weeks

    AnchorLayout:
        anchor_y: 'top'
        size_hint: 1, 0.15

        TextInput:
            text: ''
            id: text_input
            font_size: '45sp'
            input_filter: 'int'
            input_type: 'number'
            multiline: False


    GridLayout:
        cols: 2
        padding: [40, 0, 0, 0]
        BoxLayout:
            orientation: 'vertical'

            MyOwnLabel:
                text: 'Години'

            MyOwnLabel:
                text: 'Хвилини'

            MyOwnLabel:
                text: 'Секунди'

            MyOwnLabel:
                text: 'Мілісекунди'

            MyOwnLabel:
                text: 'Тижні'

        BoxLayout:
            orientation: 'vertical'
            size_hint: 0.5, 1

            MyOwnLabel:
                text: '0'
                id: label_hours

            MyOwnLabel:
                text: '0'
                id: label_minutes

            MyOwnLabel:
                text: '0'
                id: label_seconds

            MyOwnLabel:
                text: '0'
                id: label_m_seconds

            MyOwnLabel:
                text: '0'
                id: label_weeks

    BoxLayout:
        size_hint: 0.9, 0.15
        padding: [30, 20, 30, 20]
        Button:
            text: 'let go!'
            on_release:
                root.convert()