<Container>:
    orientation: 'vertical'
    padding: 30
    spacing: 30
    text_input: text_input
    label_text: label_text

    TextInput:
        id: text_input
        text: ''
        multiline: False
        font_size: 50

    Label:
        id: label_text
        text: 'Text'
        font_size: 40

    FloatLayout:
        Button:
            text: 'go'
            font_size: 40
            size_hint: 0.5, 1
            pos_hint: {'center_x': 0.5, 'y': 0}
            on_release:
                #self.text = 'New text'
                root.change_something()

